### ISSUE TITLE
Build some CI with GitHub actions

### ISSUE THREAD

**Issue by blaylockbk** [blaylockbk/Herbie#100]
I need some CI to check that Herbie can be installed and run on multiple platforms.

- Test installing Herbie on different platforms with Conda
- Run Herbie's tests with Python 3.8 - 3.10

I'm not at all experienced with this yet, but I want to learn. If anyone has some tips, please let me know.

**Comment by blaylockbk** [comment]
Specifically, it would be nice to regenerate the docs with each pull request merge.

**Comment by amotl** [comment]
Dear Brian,

thanks a stack for your efforts on Herbie. I can help you on CI matters.

With kind regards, and a happy new year,
Andreas.

**Comment by blaylockbk** [comment]
Awesome! I look forward to learning more about CI/GHA from you.

I recently updated the GEFS model template; that's why the test was failing. It should be fixed in https://github.com/blaylockbk/Herbie/commit/14d154ea0bce536eb968e358e0a5e438c19ba398. (The tests are another thing that could be cleaned up 😆. They were mostly written to prevent me from doing something that broke everything.)

Since I'm just working on Herbie in my free time, I *really* appreciate the help.

**Comment by amotl** [comment]
After rebasing, I am now getting those errors when running the test suite on my machine. It happened three times in a row. Maybe it's still a fluke, because the program is tripping over some missing upstream data?

```
FAILED tests/test_hrrr.py::test_hrrr_aws1 - EOFError: No valid message found: PosixPath('/var/folders/06/w9pzygdj7vx53n_0l9q_lhph0000gn/T/Herbie-Tests/hrrr/20230106/subset_a9effd54__hrrr.t19z.wrfsfcf...
FAILED tests/test_hrrr.py::test_do_not_remove_file - EOFError: No valid message found: PosixPath('/var/folders/06/w9pzygdj7vx53n_0l9q_lhph0000gn/T/Herbie-Tests/hrrr/20230106/subset_a9effd54__hrrr.t19z.wrfsfcf...
FAILED tests/test_rap.py::test_rap_aws - assert None is not None
```

**Comment by amotl** [comment]
> Maybe it's still a fluke, because the program is tripping over some missing or invalid upstream data?

It looks like exactly that might have happened. All errors are gone again.

**Comment by amotl** [comment]
GH-138 has a patch to run the test suite on GHA.

I tried to improve the efficiency of the Anaconda setup, but, despite using Mamba, and applying caching, it looks like it is rather heavy. I am wondering if so many resources should be wasted if there could also be a pure-Python approach. 

However, innocent-looking dependencies like `cartopy` will need the GEOS library, and this is usually difficult to setup correctly on Windows. I recognize that Anaconda is a huge benefit in this regard, so there will probably no way around it, when aiming for multi-OS testing.

**Comment by amotl** [comment]
> I tried to improve the efficiency of the Anaconda setup, but, despite using Mamba, and applying caching, it looks like it is rather heavy. I am wondering if so many resources should be wasted if there could also be a pure-Python approach.

GH-139 implements a hybrid approach, I think this brings in the best balance of platform/environment coverage vs. resource usage.

**Comment by amotl** [comment]
I think by integrating this patch, this issue can be closed.

> The tests are another thing that could be cleaned up 😆.
> [Also,] it would be nice to regenerate the docs with each pull request merge.

Let's discuss and implement those topics on behalf of other issues and patches, right?

**Comment by amotl** [comment]
Hi again. I think the items raised on this issue have been resolved, so it can be closed.
