### ISSUE TITLE
Create a conda-forge recipe so Herbie can be installed via conda

### ISSUE THREAD

**Issue by blaylockbk** [blaylockbk/Herbie#101]
It would be nice if Herbie could be installed with Conda directly, instead of using Pip. Especially since Herbie depends on cfgrib and cartopy, which have dependencies that can't be installed with pip (proj, GEOS, eccodes)

I don't have experience with this, but want to learn. If anyone can help out with this, that would be awesome 😁

- https://blog.gishub.org/how-to-publish-a-python-package-on-conda-forge
- https://docs.conda.io/projects/conda-build/en/latest/user-guide/tutorials/build-pkgs-skeleton.html
- https://github.com/conda-forge/staged-recipes/blob/main/recipes/example/meta.yaml
- https://github.com/blaylockbk/staged-recipes#getting-started

**Comment by dopplershift** [comment]
What you need is to make a PR to conda-forge's [staged-recipes](https://github.com/conda-forge/staged-recipes) repository adding a file `recipes/herbie/meta.yaml`. For information on what should be in `meta.yaml`, you can look at [metpy's](https://github.com/conda-forge/metpy-feedstock/blob/main/recipe/meta.yaml).

**Comment by blaylockbk** [comment]
Thanks for the tip @dopplershift. I always look at MetPy to pattern my stuff. Haha!

**Comment by blaylockbk** [comment]
Thanks so much @dopplershift for your direction. It was fun to learn something new, and it was a lot easier than I thought it would be. I guess by putting this on conda-forge I'm digging myself in an even deeper hole maintaining my grad school code 😆. Oh well.
