### ISSUE TITLE
Carpenter Workshop instructions missing from tutorials

### ISSUE THREAD

**Issue by williamhobbs** [blaylockbk/Herbie#108]
First, this tool is awesome. Thanks for publishing and maintaining it!

I installed your package using `conda install -c conda-forge herbie-data`, but wasn't able to run this portion of your tutorial https://blaylockbk.github.io/Herbie/_build/html/user_guide/notebooks/data_hrrr.html without first installing [Carpenter Workshop](https://github.com/blaylockbk/Carpenter_Workshop), e.g.,

`pip install git+https://github.com/blaylockbk/Carpenter_Workshop.git`

It might be helpful to add some additional instruction/details in the tutorials or here https://github.com/blaylockbk/Herbie#installation.

**Comment by blaylockbk** [comment]
Thanks for brining this up. Yep, I'll add that to the install instructions. The conda install is new and I haven't had a chance to update the docs yet. 

The Carpenter_Workshop is not a required dependency, but I'll make that clear for the tutorials.

**Comment by blaylockbk** [comment]
Docs were updated. Thanks for poking me on this several months ago.
