### ISSUE TITLE
Add interface to wgrib2 to produce subset

### ISSUE THREAD

**Issue by blaylockbk** [blaylockbk/Herbie#109]
Requested more than once...

> it is possible to set a region and some variables names to download.

No, it's not possible, but wgrib2 can subset a grib file for you after it is downloaded.

**Comment by blaylockbk** [comment]
cc: @wblumberg
You asked about this, and I'm thinking about how to do this within Herbie for downloaded files.

**Comment by williamhobbs** [comment]
@blaylockbk For anyone that might come across this in the future, your link to the docs does not appear to work. You might want to edit the last comment to update it. I think this is the link https://herbie.readthedocs.io/en/latest/user_guide/_tutorial_notebooks/wgrib2-wrapper.html.

**Comment by blaylockbk** [comment]
Done! Thanks for reporting this.
