### ISSUE TITLE
Multiple searchStrings

### ISSUE THREAD

**Issue by btickell** [blaylockbk/Herbie#110]
Is it possible to use multiple search strings in a single download call? Would like to grab several variables at once.

**Comment by blaylockbk** [comment]
Hi @btickell, You can use regular expression in the searchString argument to grab multiple variables at once. For examples, see the [docs](https://blaylockbk.github.io/Herbie/_build/html/user_guide/searchString.html) and [this discussion](https://github.com/blaylockbk/Herbie/discussions/105).
