### ISSUE TITLE
xarray datasets cannot be written with .to_netcdf() due to PosixPath attr type

### ISSUE THREAD

**Issue by coliveir-aer** [blaylockbk/Herbie#135]
Thanks for creating this library, it has been very useful in gathering data from the HRRR and GFS models for projects I am supporting.

One limitation encountered is that the xarray datasets created when loading grib data are not able to be written to netcdf with the xarray `.to_netcdf()` method without first either removing the `local_grib` attribute or changing it to a string, since it is stored as a `PosixPath` object in the attributes dictionary of the xarray dataset.

Is there any reason this attribute couldn't be stored directly as a string to mitigate this issue?

Thanks!

**Comment by blaylockbk** [comment]
Glad to hear Herbie has been helpful 😁
And thanks for the feedback. I made the change to store the path as a string in https://github.com/blaylockbk/Herbie/commit/ed2fc116e03f9a04248ccd2ffa46db2619f58baf
