### ISSUE TITLE
Add AWS as source for ECMWF data

### ISSUE THREAD

**Issue by blaylockbk** [blaylockbk/Herbie#148]
Heard at AMS that this data is or will be available on AWS

**Comment by kuchaale** [comment]
You can see a tutorial [here](https://confluence.ecmwf.int/display/DAC/ECMWF+open+data%3A+real-time+forecasts).

**Comment by blaylockbk** [comment]
Thanks!

It looks like the URL is
```
https://ecmwf-forecasts.s3.eu-central-1.amazonaws.com
```

Should be easy to update the [ecmwf.py](https://github.com/blaylockbk/Herbie/blob/main/herbie/models/ecmwf.py) template file to include the "aws" source.

Funny, this data isn't listed in the AWS registry or marketplace yet 
- https://registry.opendata.aws/
- https://aws.amazon.com/marketplace/search/
