### ISSUE TITLE
H.inventory() not working

### ISSUE THREAD

**Issue by moptis** [blaylockbk/Herbie#171]
Hello, I'm a newbie and can't seem to get the inventory function working (screeshot below). Any ideas?

![image](https://user-images.githubusercontent.com/32751681/224182669-2e67fecf-6952-4b9a-9459-3a0f9e40725f.png)

**Comment by blaylockbk** [comment]
Hi @moptis!

I'm sorry; this is a "my bad" on my part. My docs are ahead of the latest release...

The `H.inventory()` method is going to replace the `H.read_idx()` method. You can use the `H.read_idx()` method instead and it behaves the exact same way.

If you want, you can install the current main branch, or wait until the next release to use the inventory method (I've been working on it, but need a few more hours of free time to get the release out).

**Comment by moptis** [comment]
Ahhh, ok, good to know I'm not crazy!  Hah, looking forward to the new release. 

This is a really great tool. Thanks for putting this together.

**Comment by blaylockbk** [comment]
Closing since this will be fixed in the next release; hopefully coming soon :)

**Comment by blaylockbk** [comment]
Ok. I released a new version of Herbie. It's on PyPI and conda-forge. The inventory method is there. Thanks for prompting me to do this sooner rather than later.
