### ISSUE TITLE
bug: HRRR GUSTs and FRICV

### ISSUE THREAD

**Issue by peterdudfield** [blaylockbk/Herbie#177]
Hi, 

I was wondering if anyone can help. Im trying to load both "FRICV" and "GUST" from HRRR

```python
from herbie import FastHerbie
import pandas as pd
import xarray as xr

day = pd.DatetimeIndex(["2022-08-05 06:00:00"])
model = "hrrr"
product = "sfc"
fxx = [1]

for searchstring in ["GUST:", ":FRICV", ":FRICV:|:GUST:"]:

    print(searchstring)
    fh_gust = FastHerbie(DATES=day, model=model, product=product, fxx=fxx)
    files = fh_gust.download(searchString=searchstring) 
    ds = xr.open_dataset(files[0])

    print(ds_gust)
```

error:
```
  File "/Users/peterdudfield/miniconda3/envs/ercot_wind_forecast/lib/python3.11/site-packages/cfgrib/messages.py", line 273, in itervalues
    yield self.filestream.message_from_file(file, errors=errors)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/peterdudfield/miniconda3/envs/ercot_wind_forecast/lib/python3.11/site-packages/cfgrib/messages.py", line 340, in message_from_file
    return Message.from_file(file, offset, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/peterdudfield/miniconda3/envs/ercot_wind_forecast/lib/python3.11/site-packages/cfgrib/messages.py", line 96, in from_file
    codes_id = eccodes.codes_grib_new_from_file(file)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/peterdudfield/miniconda3/envs/ercot_wind_forecast/lib/python3.11/site-packages/gribapi/gribapi.py", line 413, in grib_new_from_file
    GRIB_CHECK(err)
  File "/Users/peterdudfield/miniconda3/envs/ercot_wind_forecast/lib/python3.11/site-packages/gribapi/gribapi.py", line 230, in GRIB_CHECK
    errors.raise_grib_error(errid)
  File "/Users/peterdudfield/miniconda3/envs/ercot_wind_forecast/lib/python3.11/site-packages/gribapi/errors.py", line 382, in raise_grib_error
    raise ERROR_MAP[errid](errid)
gribapi.errors.PrematureEndOfFileError: End of resource reached when reading message
```

It works for the individual variables, but not for the joint one. 

Can anyone help? I'm happy to put my versions of packages, if this is not a common problem

**Comment by blaylockbk** [comment]
Hi @peterdudfield 

I haven't seen this error before. It kind of looks like cfgrib is trying to read a file that was not fully downloaded.

Using the latest version of Herbie and cfgrib
```
herbie-data               2023.3.0
cfgrib                    0.9.10.3
```

```python
from herbie import Herbie
H = Herbie("2022-08-05 06:00", model='hrrr', produce='sfc', fxx=1,)

# Check the fields for a given searchString
H.inventory(":FRICV:|:GUST:")
```
![image](https://user-images.githubusercontent.com/6249613/227339230-5e206251-6f54-4160-9c60-ed442378fea8.png)

> ☝🏻 Note: The old `H.read_idx()` method was renamed `H.inventory()` in the last Herbie release. It is useful for checking your searchString.

```python
# Read data with xarray
ds = H.xarray(":FRICV:|:GUST:")
```
![image](https://user-images.githubusercontent.com/6249613/227339597-b82db5d3-dadb-4fe4-b658-81405d9830f1.png)



This also worked for me...
```python

file = H.download(":FRICV:|:GUST:")

import xarray as xr
ds = xr.open_dataset(file)
```

I see you are trying FastHerbie. This worked for me too.

```python
from herbie import FastHerbie
import pandas as pd

day = pd.DatetimeIndex(["2022-08-05 06:00:00"])
model = "hrrr"
product = "sfc"
fxx = [1]

fh = FastHerbie(DATES=day, model=model, product=product, fxx=fxx)
files = fh.download(":FRICV:|:GUST:")

xr.open_dataset(files[0])
```

---
Two things to check:
1. Are you using a recent version of cfgrib?
2. Was the file downloaded completely?

**Comment by peterdudfield** [comment]
Thanks @blaylockbk for getting back to quick.

Hmm interestingly if I change the date it does work. Possible something local on my computer then, sorry to bother you. For reference I'm on `cfgrib==0.9.10.3`.

**Comment by blaylockbk** [comment]
Glad to hear it worked for another date. It sounds more like an incomplete download. I'd try removing the file downloaded on your computer for that date that didn't work. You can download it manually, or tell Herbie to overwrite the existing file if it exists:

```python
H.download(searchString, overwrite=True)

H.xarray(searchString, overwrite=True
```

Closing this for now, but feel free to reopen if you have more issues.
