### ISSUE TITLE
Can I use `gh-action-pypi-publish`

### ISSUE THREAD

**Issue by blaylockbk** [blaylockbk/Herbie#178]
https://github.com/pypa/gh-action-pypi-publish

**Comment by blaylockbk** [comment]
https://dev.to/iamtekson/publish-package-to-pypi-and-release-new-version-using-github-actions-108k#:~:text=Publish%20Package%20to%20PyPI%20and%20Release%20Version%20Automation,Test%20whether%20it%20will%20work%20or%20not%20

**Comment by blaylockbk** [comment]
https://pgjones.dev/blog/trusted-plublishing-2023/

**Comment by raybellwaves** [comment]
Yes. I found the templates to be helpful and need only a little bit of tweaking: https://github.com/intake-dynamodb/intake-dynamodb/blob/main/.github/workflows/python-publish.yml
