### ISSUE TITLE
Write xarray datasets from Herbie to netcdf broken?

### ISSUE THREAD

**Issue by jlmaurer** [blaylockbk/Herbie#181]
Just recently I'm having an issue with trying to write xarray datasets accessed using Herbie to a netcdf file. Basic workflow: 
```
from herbie import Herbie
H = Herbie('2018-11-01 00:00', model='hrrr', product='prs', fxx=0)
ds_list = H.xarray("TMP", verbose=False)

# this picks out one of the datasets for writing
ds_out = None
for ds in ds_list:
    for var in ds.data_vars:
        if var in ['t']:
            if (len(ds[var].shape) == 3) & (ds[var].shape[0] > 2):
                ds_out = ds
                break

ds_out.to_netcdf('test.nc') #ds_out.to_netcdf('test.nc', engine='netcdf4') gives the same error
```
The workflow breaks at the last step with the following error: 
`TypeError: Invalid value for attr 'local_grib': PosixPath(...). For serialization to netCDF files, its value must be of one of the following types: str, Number, ndarray, number, list, tuple`

Not sure if this is a Herbie error, or xarray, or something else. Any ideas appreciated!

**Comment by coliveir-aer** [comment]
This was a Herbie error, it should be fixed as of the latest release last month.

See: https://github.com/blaylockbk/Herbie/issues/135

You can work around it without updating your version like this:
`ds.attrs["local_grib"]= str(ds.attrs["local_grib"])`

**Comment by jlmaurer** [comment]
Excellent, thank you! Problem solved.
