### ISSUE TITLE
Specify a filepath to save data to?

### ISSUE THREAD

**Issue by marcellonovak** [blaylockbk/Herbie#187]
I couldn't figure out how to specify where to write the grib file, my username folder has a space in it and it trips up on that and can't access the file.

**Comment by blaylockbk** [comment]
Thanks for reporting this. I see the problem, too.

```python
from herbie import Herbie
from pathlib import Path
```

This Doesn't work (space in folder name)...it creates the folder path if it doesn't exit, but doesn't download the file!
```python
SAVE_HERE = Path("C:\\Users\\blaylock\\Desktop\\tmp\\New folder")

H = Herbie("2023-01-01")
H.download("TMP:2 m", save_dir=SAVE_HERE)

H.get_localFilePath("TMP:2 m"), H.get_localFilePath("TMP:2 m").is_file()
```

But this does work! (no space in folder name)
```python
SAVE_HERE = Path("C:\\Users\\blaylock\\Desktop\\tmp\\New-folder")

H = Herbie("2023-01-01")
H.download("TMP:2 m", save_dir=SAVE_HERE)

H.get_localFilePath("TMP:2 m"), H.get_localFilePath("TMP:2 m").is_file()
```

**Comment by blaylockbk** [comment]
This only seems to be an issue for downloading subset files...

Downloading the full file works 🤔
```python
SAVE_HERE = Path("C:\\Users\\blaylock\\Desktop\\tmp\\New folder")

H = Herbie("2023-01-01")
H.download(save_dir=SAVE_HERE)

H.get_localFilePath(), H.get_localFilePath().is_file()
```

**Comment by blaylockbk** [comment]
@marcellonovak Thanks for reporting this bug!

![image](https://github.com/blaylockbk/Herbie/assets/6249613/2c375ebb-fe35-4451-a6f8-e34e6908748a)

I'll try to publish a new release soonish, but in the meantime you can install the latest version from GitHub

```
pip install git+https://github.com/blaylockbk/Herbie.git
```
