### ISSUE TITLE
missing docs link

### ISSUE THREAD

**Issue by raybellwaves** [blaylockbk/Herbie#193]
Thank you very much for this package!

In scrolling: https://herbie.readthedocs.io/en/stable/user_guide/_tutorial_notebooks/intro.html
I tried to click on "High Resolution Rapid Refresh (HRRR)" which points to https://herbie.readthedocs.io/user_guide/notebooks/data_hrrr.html but I get a 404 page not found.

Given all these are 404's are they meant to be hyperlinks?

<img width="445" alt="Screen Shot 2023-05-24 at 11 18 17 AM" src="https://github.com/blaylockbk/Herbie/assets/17162724/e00ac2b6-66fd-4333-82a4-b10a430b8bdb">

**Comment by blaylockbk** [comment]
Glad you like Herbie 🏁

Nice catch! Looks like I renamed the notebooks and didn't change these links. The right link is 
https://herbie.readthedocs.io/en/latest/user_guide/_model_notebooks/hrrr.html

I fixed the links in https://github.com/blaylockbk/Herbie/commit/faa1070a78a815fba4645590a5f389eceae4c9f4. They are hardcoded to the "latest" version, which is fine for now. 


![image](https://github.com/blaylockbk/Herbie/assets/6249613/42b2369c-b94e-4d7b-bdd9-6097759d88c9)
