### ISSUE TITLE
Multiple Levels Subsetting

### ISSUE THREAD

**Issue by FireWx42** [blaylockbk/Herbie#20]
When using the subset function and attempting to subset multiple levels (t2m, surface, 10m wind, etc), xarray does not open all variables, only attained surface variables. Wondering if this has to do with Herbie or xarray. Thought I would make you aware of this.

**Comment by FireWx42** [comment]
When using xarray and subsetting the backend_kwargs to look at the heightAboveGround variable, I can access the data in the cfgrib file. Potentially a cfgrib problem only. Closing.

**Comment by blaylockbk** [comment]
You might want to look at `cfgrib.open_datasets(file)` instead of `xarray.open_dataset(file)` 
👉🏻https://github.com/ecmwf/cfgrib#automatic-filtering

**Comment by FireWx42** [comment]
Thanks, forgot about that option!
