### ISSUE TITLE
looking for HRRR XLAT_C and XLONG_C

### ISSUE THREAD

**Issue by bsu-wrudisill** [blaylockbk/Herbie#203]
Hello

Thanks for making HRRR data so much easier to access

I am trying to find the location of the corner lat/lons for the HRRR domain -- these are normally in the XLAT_C and XLONG_C variables in WRF. Are these variables available somewhere? I suppose there is a way to compute this from the projection information, but I don't have a solution for that at hand 

Cheers
Will

**Comment by blaylockbk** [comment]
It sounds like you're familiar with WRF output (I actually haven't run WRF in 5+ years). If I remember right, WRF output is NetCDF. Something to keep in mind is that Herbie is retreiveing the HRRR _GRIB2_ files, which are structured differently than NetCDF.

If you read the GRIB2 file with xarray/cfgrib, its pretty straightforward to get the latitude and longitude of each grid point:

```python
from herbie import Herbie
H = Herbie('2023-01-01 00:00', model='hrrr')
ds = H.xarray("TMP:2 m")

ds.longitude

ds.latitude
```

**Comment by blaylockbk** [comment]
Also, if I remember right, WRF lets you get the lat/lon grid points for the Arakawa grid and the regular grid. The GRIB2 files (I don't think) have that distinction, e.g., values for wind and temperature are at the same point and are not staggered like you might get in WRF.

**Comment by bsu-wrudisill** [comment]
Gotcha, yes I was just assuming that HRRR has these variables somewhere (since it's WRF under the hood AFAIK). Thanks for pointing that out, I didn't realize that staggered variables aren't in the grib files.

Also, I double-checked and XLAT_C and XLONG_C aren't actually stored in typical wrfout files, but rather the geographic domain files (geo_em.X.nc in WRF parlance) so I'm not so sure I'll be able to find them... 

(For what it's worth I'm trying to plot the footprint of a single 3x3 km HRRR grid cell on a map -- there must be a way to do this knowing the center lat/lon provided, the resolution of the grid cell, the projection, and grid rotation(?), but the solution is eluding me at the moment) 

Feel free to close this, and sorry it's a little beyond the scope of this great tool! Thanks for the help

**Comment by rodinia814** [comment]
Something like this?

```

def get_cell_coords (ds: xarray.Dataset, x: int, y: int) -> list:
    y_len = len(ds.latitude['y']) # 1059
    x_len = len(ds.latitude['x']) # 1799
    if x < 0 or x >= x_len:
        raise Exception("x dim out of bounds")
    if y < 0 or y >= y_len:
        raise Exception("y dim out of bounds")

    lllat = ds.latitude[y][x].values - 0
    lllong = ds.longitude[y][x].values - 360
    urlat = ds.latitude[y+1][x+1].values - 0
    urlong = ds.longitude[y+1][x+1].values - 360
    return [lllat, lllong, urlat, urlong]
```
