### ISSUE TITLE
Consider giving talk at 104th AMS Meeting

### ISSUE THREAD

**Issue by blaylockbk** [blaylockbk/Herbie#216]
I am considering giving a talk about the **Herbie** python package at the 104th American Meteorological Society Annual Meeting[^1]. This talk would be given at the [14th Symposium on Advances in Modeling and Analysis Using the Programming Languages of Open Science](https://annual.ametsoc.org/index.cfm/2024/program-events/conferences-and-symposia/14th-symposium-on-advances-in-modeling-and-analysis-using-the-programming-languages-of-open-science/)

> ### Proposed title:<br> How and why I build Herbie: A python package for accessing numerical weather prediction data.
>
> Affiliation: Myself (because no one sponsors Herbie)

Possible outline of talk:

1. Purpose of Herbie 
    - "Herbie bridges the gap between where NWP data is located (NOMADS, AWS, etc.) and the analysis tools used to process the data (xarray+cfgrib)."
2. Quick history on Herbie and examples of basic usage
3. Encourage others (especially students and young scientists) to participate in open science, learn GitHub, and publish their code. _This would be the main purpose of my talk._
    - I didn't think Herbie would be noticed or used by anyone, but I am pleased that people find it useful. While working on Herbie I have developed skills that are valuable to my employer--enhanced software development ability, learned how to use GitHub effectively, expanded my network.

---

Would people be interested in hearing me talk about Herbie? I admit that Herbie is not the most neatly written or maintained package (I spend a few hours a month on it). Still, maybe telling my story would be of interest to the audience. Any thoughts?

[^1]: Of course, my attendance depends on if my employer sends me to the meeting to give another unrelated talk; likelihood is high.

**Comment by blaylockbk** [comment]
Hi @scollis, since you have tried Herbie and are the chair of the Symposium, I wanted to PING you with my idea for a possible talk ☝🏻

I'm open to feedback if you have any.

**Comment by bryanguarente** [comment]
@blaylockbk Like I did with goes2go, I am working on another viewer using your Herbie codebase to grab different model outputs and plot them on the fly.  I have a poor version of it right now, and I am considering, like you suggested, making the viewer with panel and holoviz instead of ipywidgets.  If you are interested in that as an end product from your work, that might be a nice ending to a talk.  Just food for thought.

**Comment by blaylockbk** [comment]
Abstract was submitted.
