### ISSUE TITLE
Only download a certain bounded box (region)

### ISSUE THREAD

**Issue by andrew-moldovan** [blaylockbk/Herbie#231]
Hey, thanks for building this, awesome tool! I'm working on a project where I need many years of historical data for a few variables (temp, precip, etc...), but only for very small regions. 

So my code right now is something like this:

```
DATES = pd.date_range(
    start="2022-12-24 06:00",
    periods=15, #just testing things here, actual value will be much larger
    freq="1D",
)

fxx = range(2, 26)

FH = FastHerbie(DATES, model="hrrr", fxx=fxx)

ds = FH.xarray("TMP:2 m", remove_grib=False)
ds = ds.herbie.nearest_points(points=location)
```

Which works great, but it ends up downloading way more data than I need. Not sure if it would be possible to "subset" the data so we're only downloading what we need for the region we're looking at?

**Comment by blaylockbk** [comment]
Hi @andrew-moldovan
Glad you like Herbie.

The inability to subset GRIB files into smaller regions when you download is one of the downfalls of the GRIB format. However, the University of Utah maintains the HRRR archive in zarr format, which sounds like based on what you need is a perfect reason to use that archive.

You can read more here... 
https://mesowest.utah.edu/html/hrrr/

**Comment by andrew-moldovan** [comment]
Ok thanks for the information! I'll close this ticket then
