### ISSUE TITLE
PermissionError when attempting to create config file

### ISSUE THREAD

**Issue by gmgunter** [blaylockbk/Herbie#243]
I have an application that involves using Herbie from within a Docker container. The usage of the container is a bit heterodox in that the user will typically run the container with their own user ID (on the host) rather than as the image's default user. In general, therefore, the user does not have a home directory inside the container and `$HOME` will expand to `/`.

This is causing some issues with importing Herbie. Herbie attempts to create a fresh config file within the root directory, where it doesn't have write permissions.

```
$ echo $HOME
/
$ python3 -c "import herbie"
 ╭─────────────────────────────────────────────────╮
 │ I'm building Herbie's default config file.      │
 ╰╥────────────────────────────────────────────────╯
 👷 🏻‍♂️
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/pathlib.py", line 1323, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/.config/herbie'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python3.9/site-packages/herbie/__init__.py", line 136, in <module>
    _config_path.parent.mkdir(parents=True, exist_ok=True)
  File "/opt/conda/lib/python3.9/pathlib.py", line 1327, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/opt/conda/lib/python3.9/pathlib.py", line 1323, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/.config'
```

Would it be possible to add a workaround for the case where the user's home directory is not writeable? Some potential solutions for my use case would be: (A) allow the user to override the default location of the config file, or (B) fall back to using the default settings if we fail to create the config file (as suggested in [this comment](https://github.com/blaylockbk/Herbie/issues/223#issuecomment-1672371068)).

**Comment by cmo84** [comment]
I've encountered this also.  You can add a writable /.config/herbie/ folder in the container image and a /data folder in order to allow Herbie's default behavior to play well with the container.  You can also drop a config.toml file in there which changes the options and save_dir like this:

    /.config/herbie/config.toml :
```
[default]
model = "hrrr"
fxx = 0
save_dir = "/tmp"
overwrite = false
verbose = false
```

**Comment by gmgunter** [comment]
Thanks @cmo84 for the suggestion. I might implement something like this as a workaround for now. Ideally, though, I would prefer if there was a solution that didn't require cluttering the root directory of the container's filesystem.

**Comment by blaylockbk** [comment]
Thanks for sharing this feedback. I don't have experience running Herbie in Docker, so thanks for bringing this up. It sounds like Herbie needs to function without a config file. 

1. I don't know yet how to implement a solution where a user can tell Herbie where to write the config file without hard coding the path in the Herbie source code. I'll have to think about that.

2. The easy solution is that Herbie should use some defaults if a config is not found and it's not able to create the file. This is fine, except for one potential hiccup...the config file defines where the data is downloaded in `save_dir`. You could run into the same problem that the default might point to a path that a user doesn't have permissions to write. Hmmm. Maybe the default `save_dir` should be the current working directory??

I'm just throwing out my initial thoughts. If you have any other ideas or want to make a pull request, let me know. When I get some time to work on this, I think I'll try **Idea 2** first and see if that can work.

**Comment by blaylockbk** [comment]
@gmgunter 
Hopefully #253 will help your case. I made it so that if Herbie can't read/create its config file, then it will load some default settings.

Please reopen or create a new issue if you continue to have trouble.
