### ISSUE TITLE
GEFS on Azure and Google

### ISSUE THREAD

**Issue by williamhobbs** [blaylockbk/Herbie#247]
I can pull GEFS from AWS but not from Google or Azure. I'm not sure how to browse Azure, but for Google it looks like the data I'm requesting is available. I'd be fine with only using AWS, but I sometimes have firewall issues with AWS, and mentioned in https://github.com/blaylockbk/Herbie/issues/246, and using Azure or Google for GEFS would be a good workaround. 

Example, this

```python
H = Herbie(
    "2023-01-01 00:00",  # model run date
    model="gefs",  # model name
    product="atmos.5",  # model product name (model dependent)
    fxx=36,  # forecast lead time
    member='p01',
    priority="aws"
)
```
returns:
```
✅ Found ┊ model=gefs ┊ product=atmos.5 ┊ 2023-Jan-01 00:00 UTC F36 ┊ GRIB2 @ aws ┊ IDX @ aws
```

while

```python
H = Herbie(
    "2023-01-01 00:00",  # model run date
    model="gefs",  # model name
    product="atmos.5",  # model product name (model dependent)
    fxx=36,  # forecast lead timet
    member='p01',
    priority="azure"
)
```
returns:
```
💔 Did not find ┊ model=gefs ┊ product=atmos.5 ┊ 2023-Jan-01 00:00 UTC F36
```

**Comment by blaylockbk** [comment]
We just need to add the URL for azure and google in these lines...

https://github.com/blaylockbk/Herbie/blob/097600675dad6eecc799e9e404bba6123cb06a52/herbie/models/gefs.py#L80-L83

It might take me a week or two before I can get to it; you could try to beat me to it with a PR 😁

**Comment by blaylockbk** [comment]
I'll close this for now after merging #248. Please reopen if you have other issues.

**Comment by williamhobbs** [comment]
Thanks! And thanks for encouraging me to submit a PR - I assumed it would be more difficult, and didn't look into it until you mentioned the need for the updated URLs.

**Comment by blaylockbk** [comment]
And thanks for contributing!
