### ISSUE TITLE
Contributing Guidelines link in readme not working

### ISSUE THREAD

**Issue by williamhobbs** [blaylockbk/Herbie#249]
The link to the Contributing Guidelines in the readme, https://herbie.readthedocs.io/user_guide/contribute.html, doesn't seem to be working. 

![image](https://github.com/blaylockbk/Herbie/assets/45701090/6f383b15-42dc-4ebd-8f73-5877c37e2cc7)

**Comment by blaylockbk** [comment]
Ah, good find. Yeah, I moved that to this page.

https://herbie.readthedocs.io/en/stable/user_guide/disclaimer.html

I'll update the link in the README.
