### ISSUE TITLE
Control member exist in atmos.5b product from GEFS model

### ISSUE THREAD

**Issue by byphilipp** [blaylockbk/Herbie#267]
Control member exist in atmos.5b product from GEFS model but unavailiable in Herbie 

Fix it in models/gefs.py line 61
Replace
`            "atmos.5b": [f"p{i:02d}" for i in range(1, 31)],`
To
`            "atmos.5b": [f"p{i:02d}" for i in range(1, 31)]+['c00'],`

Thank you so much

**Comment by blaylockbk** [comment]
Thanks for catching this 😃
