### ISSUE TITLE
Several issues with HerbieWait

### ISSUE THREAD

**Issue by karlwx** [blaylockbk/Herbie#280]
I'm pleased to discover the addition of HerbieWait! I saw that in the docs you mentioned that it has yet to be tested. I tested it today, and am finding several issues. 

The first issue is more so related to functionality - the default behavior is to search for the model run closest to the current hour (no option to change it), but for practical purposes, we should be able to specify the model run. In some cases (e.g. ECMWF), the user might not want to begin waiting for data until it's actually available (6+ hours after run time). 

I attempted to tweak the code to allow for this, but ran into other issues. For some reason, the Herbie object is returning None, and the TimeoutError appears to be in the wrong place (raises a TimeoutError upon success in finding the file).

Sample script for testing:
```python
from herbie.latest import HerbieWait
from datetime import datetime
import numpy as np

run = datetime(2024,1,25,12)
fhrs = np.arange(0,246,6)
for fhr in fhrs:
    H = HerbieWait(run, priority="ecmwf", model="ecmwf", product="oper", fxx=int(fhr), save_dir='./data/model/', overwrite=True,
                  wait_for="3hr", check_interval="1min")
    H.download(":2t:")
```

Thanks for looking into this!

**Comment by blaylockbk** [comment]
Thanks for trying it and sending this feedback! If you want to take a stab at making this work better, you're welcome to make a PR. I probably won't get around to this for a while.

**Comment by charlie-becker** [comment]
@karlwx I can see the utility in wanting to specify a model run and wait for specific forecast hours to populate, especially in cases where a model might still be populating runs when the UTC hour changes.

`HerbieWait()` currently overrides your initialization time (run), thus causing the issues your seeing. 

> and the TimeoutError appears to be in the wrong place (raises a TimeoutError upon success in finding the file).

This is implemented correctly, it successfully `returns` without Error upon finding a `.grib` attribute.

You might be successful just eliminating the date / init and loop through the forecasts hours the same way. Again though, a potential problem arises if the top of the hour passes within the loop.

A simple solution might be to just check if a `date` argument has been passed, and only override it with `now` if it doesn't exist.

**Comment by charlie-becker** [comment]
@karlwx 
>  the user might not want to begin waiting for data until it's actually available (6+ hours after run time).

I think this defeats the whole purpose of using `HerbieWait()`. I believe the whole idea is to grab it as soon as it's possibly available. If you (not Herbie) waits until the data is available, why not just loop through Using core `Herbie()`? Am I missing something?

**Comment by karlwx** [comment]
> I think this defeats the whole purpose of using `HerbieWait()`. I believe the whole idea is to grab it as soon as it's possibly available. If you (not Herbie) waits until the data is available, why not just loop through Using core `Herbie()`? Am I missing something?

Yes, I think you're missing my point. Consider the ECMWF: the 12z data doesn't start becoming available until around 18z normally, so there's no point in having a script ping the server for 6 hours when you know there won't be any data. I'd set it up to look for the 12z data at a time when I'd expect it to be available.

**Comment by karlwx** [comment]
Here's what I've been working on recently, using the RAP model as a test case. It seems to have been working fine over the past few weeks. My only concern would be inadvertently grabbing partial files (in the case that the file exists, but data is still being written to it). It would be straightforward to check to see if the number of variables in the index file matches the number that's expected.

```python
model_kwargs = dict(model="rap", priority=["aws"], fxx=fhr, product="awp130pgrb")
H = Herbie(init, **model_kwargs)

start = datetime.now()
while (H.idx is None) or (H.grib is None):
    time.sleep(retry_interval)
    
    elapsed = datetime.now() - start
    if elapsed.total_seconds() > timeout:
        raise TimeoutError('Data download timed out')

    try:
        H = Herbie(init, **model_kwargs)
        if (H.idx is not None) and (H.grib is not None):
            break
    except:
        pass

H = Herbie(init, **model_kwargs)
process_fhr(H, maps, fhr)
```
