### ISSUE TITLE
Unable to fetch recent ECMWF data

### ISSUE THREAD

**Issue by cole-p** [blaylockbk/Herbie#284]
According to the [ECMWF Open Data docs](https://confluence.ecmwf.int/display/DAC/ECMWF+open+data%3A+real-time+forecasts+from+IFS+and+AIFS), the file naming convention for forecast data has changed to include a new `model` field. This field can be one of two options:
1) `ifs` (Integrated Forecast System) - open data published before this change would fall under this category
2) `aifs` (Artificial Intelligence/Integrated Forecasting System) - a new ML-based model

We will need to update the ECMWF class to use a different [post_root](https://github.com/blaylockbk/Herbie/blob/a45da720e2c1a94a64b5b86e4b39a8c3175c7dd2/herbie/models/ecmwf.py#L48) for forecasts run on/after `2024-02-28T06:00 UTC`.

The new `post_root` should look something like:

```python
self.model = "ifs"
...
post_root = f"{self.date:%Y%m%d/%Hz}/{self.model}/{version}/{self.product}/{self.date:%Y%m%d%H%M%S}-{self.fxx}h-{self.product}-{product_suffix}.grib2"
```

![image](https://github.com/blaylockbk/Herbie/assets/26638017/7cb3cc6b-688e-46aa-81bb-e0fe87036e74)

I should be able to work on a fix for this next week if nobody else gets to it first.

**Comment by blaylockbk** [comment]
Hi @cole-p! Take a look at #283 for an active pull request.

**Comment by blaylockbk** [comment]
#283

**Comment by cole-p** [comment]
Great, thank you!
