### ISSUE TITLE
ECMWF 0.4 degrees resolution forecast data will be deprecated in May 2024

### ISSUE THREAD

**Issue by cole-p** [blaylockbk/Herbie#285]
ECMWF has added a section to their [Open-Data docs](https://www.ecmwf.int/en/forecasts/datasets/open-data) indicating that products produced at 0.4 degrees resolution will be deprecated in May 2024. After that time ECMWF will switch over to only providing data at 0.25 degrees resolution.

From a quick glance in the ECMWF S3 bucket, ECMWF appears to have been publishing data at both 0.4 and 0.25 degrees resolution starting on `2024-01-31T06:00 UTC`.

Currently the resolution is hard-coded in the [version field](https://github.com/blaylockbk/Herbie/blob/a45da720e2c1a94a64b5b86e4b39a8c3175c7dd2/herbie/models/ecmwf.py#L22) of the `ecmwf` class.

**Comment by blaylockbk** [comment]
Thanks for sharing this news! Yeah, let's get this in Herbie 😄 I'll set aside some time in the next week to review pull request

**Comment by blaylockbk** [comment]
completed in #283. Feel free to provide any more comments and PRs on the topic if you see anything.

#283 makes this change

First, model can be either `ifs` or `aifs`, not `ecmwf`
```python
# Deprecated
Herbie(date, model='ecmwf')

# New
Herbie(date, model='ifs')
Herbie(date, model='aifs')
```

Also, you can specify `resolution` in `model='ifs'` so you can still access the historical data
```python
Herbie('2024-02-25', model='ifs', resolution='0p4')
```

---

I'm going to update the tutorial notebook in the docs and publish a new Herbie release this weekend.
