### ISSUE TITLE
Cisco Umbrella breaks Herbie in weird ways

### ISSUE THREAD

**Issue by dplarson** [blaylockbk/Herbie#288]
**Preface:** This isn't really an issue with Herbie and therefore this issue should likely be closed after creation. However, I thought it still worthwhile to create the issue, if only to give others a search result if they run into this issue.

**TL;DR:** Cisco Umbrella messes with HTTPS headers, which then breaks Herbie in weird ways that are not the fault of Herbie.

Keywords: Cisco Umbrella, SSL certificate, SSL errors, SSL decryption, empty grib2 file

## Background 1: curl
Herbie uses the `curl` CLI tool to download grib2 files from various sources (NOMADS, AWS, etc.). Herbie supports downloading a subset of variables within a grib2 file using `curl --range <byte range> <remote grib2 file>`, where Herbie gets the byte range for the specified variable(s) from the associated `.idx` file for the `.grib2` file.

But underneath, the `curl --range <byte range> <remote grib2 file>` is simply doing a HTTP `GET` call with the `Range` HTTP request header. Which means you could instead use other HTTP tools, such as the Python Requests package, to get the same result.

## Background 2: Cisco Umbrella
Cisco Umbrella is a "secure internet gateway (SIG)" platform. I won't get into all the details, but the key pieces of info (as I understand it) are that Cisco Umbrella:
1. is an IT security product deployed in corporate/private networks
2. uses SSL decryption to inspect HTTPS traffic

This is supposed to happen seemlessly, where users don't do anything different but now their actions are more secure. However, in practice, Cisco Umbrella can break a range of actions that rely on HTTPS. For example, installing Python packages using pip. Again, the details don't particularly matter except to say that Cisco Umbrella can mess up HTTPS and the only indication of a problem is an SSL certificate error.

## The Problem
My team has observed an odd behavior with Herbie that wasn't immediately clear was tied to Cisco Umbrella and what it does to HTTPS traffic:

If you do not have the Cisco Umbrella root certificate installed:
- attempts to download a full grib2 file using Herbie will fail
- attempts to download a subset of a grib2 file will fail

where any downloaded grib2 files will be empty (zero bytes) but the standard error messages from Herbie will not indicate an SSL error. However, if you run low-level portions of the Herbie code directly, then you will see errors related to SSL. Those SSL errors are also similar to other tools where we've faced this problem, e.g., `pip install`. But in my team's experience, the errors are vague and most people wouldn't make the connection to Cisco Umbrella unless someone else told them about this problem/behavior.

If instead you do have the Cisco Umbrella root certificate installed, then you will observe:
- attempts to download a full grib2 file using Herbie will succeed, with the local grib2 file matching the remote grib2 file
- attempts to download a subset of a grib2 file using Herbie will appear to succeed, but the local grib2 file will be the full grib2 file (instead of the smaller subset file as requested)

From our investigation, we have figured out that Cisco Umbrella is messing with the HTTP request headers, resulting in the `Range` header being removed. We're still not sure if there's something specific about the `Range` header or if more generally all HTTP request headers are being affected. But this explains what is happening when the Cisco Umbrella root certificate is installed:
- if you try to download a full grib2 file, then the `curl` command doesn't add any HTTP headers and so things work fine
- if you try to download a subset of a grib2 file, then Herbie does the `curl --request` version, which creates a HTTP GET call with a `Range` header, but then Cisco Umbrella removes the header, thereby transforming the request into one for the full grib2 file

This also confirms that this is not an issue inherently with Herbie or `curl`, or with the sources for the grib2. For example, we were able to replicate the problem using the Python Requests package with a HTTP GET with a `Range` header, which we tested on grib2 files and other file types (e.g., images).

## The Fix
We don't have a general fix and still have open questions, but those may be more specific to my company's IT setup. However, we were able to confirm that if you are on a system without Cisco Umbrella (or if certain Cisco Umbrella settings are disabled), then things work as expected with Herbie (and with calling `curl` directly or with Python Requests or any other HTTP tool). This includes for both downloading full grib2 files and subsets of the grib2 files (e.g., a few variables).

Additionally, while this issue is about Cisco Umbrella, I wouldn't be surprised if others run into similar/related problems from other corporate/private network restrictions or tools.

**Comment by blaylockbk** [comment]
Thanks for sharing this issue, and in such detail. I really appreciate it (and I'm sure someone else will run into this down the road, too).

**Comment by dplarson** [comment]
No problem. But do feel free to close this issue since it isn't really an issue with Herbie.

**Comment by williamhobbs** [comment]
@dplarson, FYI, the latest Herbie release ([2025.10.0](https://github.com/blaylockbk/Herbie/releases/tag/2025.10.0)) uses `requests` instead of `curl`, so some of this behavior may have changed. In my limited experience, troubleshooting/addressing corporate network certificate issues with `requests` is a bit easier than `curl`.
