### ISSUE TITLE
Reproject AIFS Data

### ISSUE THREAD

**Issue by karlwx** [blaylockbk/Herbie#289]
I know this was addressed in the docs, but just wanted to open an issue here to hopefully get more eyes on the problem. Evidently, someone has figured it out because several model websites are now plotting the AIFS data.
The ECMWF AIFS data reads with a single horizontal dimension "values" instead of 2 dimensions x and y.

Example of what the 2m temperature data looks like:
```
xarray.Dataset
Dimensions:
values: 542080
Coordinates:
time
()
datetime64[ns]
2024-03-06
step
()
timedelta64[ns]
6 days
heightAboveGround
()
float64
2.0
latitude
(values)
float64
...
longitude
(values)
float64
...
valid_time
()
datetime64[ns]
...
Data variables:
t2m
(values)
float32
...
gribfile_projection
()
object
None
Indexes: (0)
Attributes: (12)
```

Someone showed a workaround here:
https://github.com/ecmwf/ecmwf-opendata/issues/36
But I don't know enough CDO to produce the grid file they're using to remap the AIFS data to a 0.25 degree grid.

**Comment by karlwx** [comment]
The problem seems to have fixed itself!

**Comment by blaylockbk** [comment]
Nice! I'm not sure what changed, but I'm glad it did 😎
