### ISSUE TITLE
Feature Request: Ability to Download NBM QMD Data

### ISSUE THREAD

**Issue by fleegs79** [blaylockbk/Herbie#300]
Hello,

If possible, it would be great to add the QMD data (QPF/Precip probabilities and percentiles) as a download option for the NBM. The data is available on AWS and NOMADS, but instead of being in the "core" folder, it's in the "qmd" folder.  As a test, I swapped core with qmd in the nbm.py file for the AWS download link and I was able to view the QMD inventory and download the data.  

The data is available for all of the currently listed "Products" for the NBM. 

Thank you for the consideration,

fleegs79

**Comment by blaylockbk** [comment]
This shouldn't bee too difficult. I can't promise I'll get around to it soon, but if you want to open a PR, I think all that needs to be modified is the template file https://github.com/blaylockbk/Herbie/blob/main/herbie/models/nbm.py

**Comment by blaylockbk** [comment]
closed by #301
