### ISSUE TITLE
Update ECMWF serchStrin_help

### ISSUE THREAD

**Issue by williamhobbs** [blaylockbk/Herbie#307]
I think this needs to be updated now that ECMWF makes more parameters available. For example, 100 meter (metre) wind.

https://github.com/blaylockbk/Herbie/blob/f31d06c79264639131caf0491230c9d2f392b34e/herbie/help.py#L57-L102

**Comment by blaylockbk** [comment]
I don't see the 100-m wind product. Can you point me to it?

**Comment by williamhobbs** [comment]
If I run 

```python
H=Herbie('2024-4-18 ', model='ifs', product='oper', fxx=39)
H.inventory().param.unique()
```

it returns:

```
array(['tp', 'cape', '10v', 'gh', 'u', 'v', 'r', '100v', 't', '100u',
       'skt', 'ssrd', 'sp', 'st', 'swvl1', 'msl', 'swvl2', '10u', '2d',
       'swvl4', '2t', 'stl4', 'swvl3', 'stl2', 'stl3', 'ssr', 'w', 'tcwv',
       'q', 'lsm', 'strd', 'd', 'str', 'vo', 'ro', 'asn', 'ttr'],
      dtype=object)
```

Not sure if that's the cleanest way to do it, but it includes `100u` and `100v`. `ssrd` is also new and useful.

**Comment by blaylockbk** [comment]
Ah gotcha. I was looking at a date older than the new dataset. Thanks.

**Comment by blaylockbk** [comment]
I updated some examples in https://github.com/blaylockbk/Herbie/commit/3201f13ce4cf84ff878772634d3a0c743ba069bc. Thanks for the suggestion.
