### ISSUE TITLE
Include GFS data from NCEI and/or RDA

### ISSUE THREAD

**Issue by blaylockbk** [blaylockbk/Herbie#325]
https://www.ncei.noaa.gov/products/weather-climate-models/global-forecast

**Comment by raulv48** [comment]
I just tweak Herbie today to work with NCEI GFS. This will be a welcomed addition.

**Comment by blaylockbk** [comment]
GFS is also archived on RDA, but these files don't have .idx files with them which makes variable subsetting impossible.

https://rda.ucar.edu/datasets/d084001/

**Comment by blaylockbk** [comment]
GFS on NCEI is spotty at best

Example:
https://www.ncei.noaa.gov/data/global-forecast-system/access/grid-003-1.0-degree/analysis/

**Comment by blaylockbk** [comment]
Closed for these reasons

- GFS files at NCEI via HTTPS are spotty. Not sure it's worth making a Herbie template for this.
- GFS file access from NCAR RDA was implemented in #358, but given there is no inventory file, the user has no choice but to download the full file. You could generate the inventory for the file with wgrib2 after the file is downloaded as described [here](https://herbie.readthedocs.io/en/stable/user_guide/tutorial/wgrib2-wrapper.html).

**Comment by raulv48** [comment]
> @raulv48 With this are you able to access GFS runs prior to 2021?

@vwgeiser Yes, I was able to download NCEI data from 2020.

Sorry for the late comment on a closed ticket. Just wanted to answer as it is possible by updating the NCEI template.

**Comment by blaylockbk** [comment]
Opening this again because I see what you mean about being able to get 2020 GFS data


I can see a fair amount of analysis data available from May-Dec 2020. There isn't much available before those dates.
![image](https://github.com/user-attachments/assets/ee0657a5-4465-41d4-be97-cd1166d4effd)

I'll update the template.
