### ISSUE TITLE
Waiting for Numpy 2.0 support: numpy.dtype size changed error 

### ISSUE THREAD

**Issue by rafa-guedes** [blaylockbk/Herbie#330]
Just a heads up pygrib (and hence herbie-data) seems to be broken with the latest major release v2 from numpy. I have opened an issue in pygrib - https://github.com/jswhit/pygrib/issues/251.

**Comment by blaylockbk** [comment]
Thanks for the heads up.

**Comment by rafa-guedes** [comment]
They have released a new version with a fix! https://github.com/jswhit/pygrib/issues/251
