### ISSUE TITLE
Add 13km GFS product

### ISSUE THREAD

**Issue by byphilipp** [blaylockbk/Herbie#333]
GFS model produced a highres fields on 1536*3072 grid (about 0.117 degree / 13 km)
For example
https://nomads.ncep.noaa.gov/pub/data/nccf/com/gfs/prod/gfs.20240625/00/atmos/gfs.t00z.sfluxgrbf024.grib2.idx

**Comment by blaylockbk** [comment]
Good idea. I can't promise I'll get around to this soon, but will add it when I can (if no one else beats me to it). Would just need to modify the GFS template, specifically the PRODUCT dictionary and make sure the URLs are valid.
https://github.com/blaylockbk/Herbie/blob/e517c81af56771e4d767c8a658e8bdcd080210b8/herbie/models/gfs.py#L39-L47

**Comment by blaylockbk** [comment]
@byphilipp I haven't fully tested the added capability to get sfluxgrb data #358. I'll try to get to it soon. I _think_ the way I have it will work. If you happen to test it before I do and see an issue, please reopen this.
