### ISSUE TITLE
herbie.archive download issues

### ISSUE THREAD

**Issue by yueyin1992** [blaylockbk/Herbie#34]
Hi Brain,

Thank you for creating Herbie! I had an issue with downloading HRRR sub-hourly data. It would be much appreciated if you can help! I'm using the recent released Herbie. 
So I edited the parameters as follows. However, I got the warning saying that file is not found. I wonder if I miss anything.

```python
H = Herbie(
    '2016-10-09 00:00',
    model='hrrr',
    product='subh', #subh
    fxx=0
)
```

I tried to change the product to "sfc" just for testing and the file is found this time. However, when using `H.download(":UGRD:10 m")`. An error came out:
```
TypeError: _searchString_help() takes 0 positional arguments but 1 was given
```

Thanks so much!

Yue

**Comment by blaylockbk** [comment]
It appears that for older HRRR versions, the filenames for subh files are a little different.

Current naming method:
```
hrrr.t00z.wrfsubhf00.grib2.idx   # the analysis, F00
hrrr.t00z.wrfsubhf01.grib2.idx   # contains the 15, 30, 45, and 60 min forecasts (relative to F00)
hrrr.t00z.wrfsubhf02.grib2.idx   # contains the 75, 90, 105, and 120 min forecasts (relative to F00)

**etc.**
```

Old naming method:
```
hrrr.t00z.wrfsubhf0000.grib2.idx  # the analysis, F00
hrrr.t00z.wrfsubhf0015.grib2.idx  # the 15 min forecast
hrrr.t00z.wrfsubhf0030.grib2.idx  # the 30 min forecast
hrrr.t00z.wrfsubhf0045.grib2.idx  # the 45 min forecast
hrrr.t00z.wrfsubhf0100.grib2.idx  # the 60 min forecast
hrrr.t00z.wrfsubhf0115.grib2.idx  # the 75 min forecast
hrrr.t00z.wrfsubhf0130.grib2.idx  # the 90 min forecast
hrrr.t00z.wrfsubhf0145.grib2.idx  # the 105 min forecast
hrrr.t00z.wrfsubhf0200.grib2.idx  # the 120 min forecast

**etc.**
```

It appears this change happened on or around `datetime(2018, 9, 16)`

Herbie isn't currently configured for this.

**Comment by blaylockbk** [comment]
I made a quick and ugly fix in the branch above.

It requires an additional parameter, `fxx_subh`
```
H = Herbie(
    '2016-10-09 00:00',
    model='hrrr',
    product='subh', #subh
    fxx=1,
    fxx_subh=15
)
```

Here's a screenshot of my playing around
![image](https://user-images.githubusercontent.com/6249613/148139369-002e4848-c5d9-4153-b735-16ccff39101c.png)
