### ISSUE TITLE
HRRR native subsetting

### ISSUE THREAD

**Issue by richardgarmong** [blaylockbk/Herbie#41]
Might be slightly an edge case but when trying to subset in a native file 
```
H = Herbie('2021-07-19',
           model='hrrr',
           product='nat')
H.xarray(":(U|V)GRD:")
```
Produces " No GRIB messages found. There might be something wrong with searchString=':(U|V)GRD:hybrid'"
`H.xarray("(U|V)GRD")`  works but does a list of xarray datasets at each hybrid level rather than an xarray dataset with a hybrid dimension

**Comment by blaylockbk** [comment]
Hi @richardgarmong,

This is a good example I should include in the documentation. The solution is a nice exercise in regular expression (and some knowledge of Herbie's inner working); I think what you want is

```python
from herbie.archive import Herbie
H = Herbie(
    '2021-07-19',
    model='hrrr',
    product='nat'
)

ds = H.xarray(":(?:U|V)GRD:[0-9]+ hybrid")
```
> this took ~1 min to run (variable due to your download speed)

---

The way I debugged this was I looked at the index DataFrame to see what GRIB messages are found using different regular expression searches.

```python
# Show full index file (as a pandas DataFrame)
H.read_idx()

# Subset messages for all u and v winds
H.read_idx(searchString=":(U|V)GRD:")
# ^ this search includes wind on hybrid levels *and* height above ground levels.

# Subset messages for all u and v winds grids on just hybrid levels
H.read_idx(searchString=":(?:U|V)GRD:[0-9]+ hybrid")
# ^ this search gets wind fields on hybrid levels; it excludes the wind at above ground levels
```

What you did with `dss = H.xarray(":(U|V)GRD:")` actually returned three xarray.Datasets:
1. `dss[0]` is ds for winds at 80-m above ground
2. `dss[1]` is ds for winds at 10-m above ground
3. `dss[2]` is ds for winds at the 50 hybrid levels 

> uff, running `H.xarray(":(U|V)GRD:[0-9]+ hybrid")` again took my computer a long time. I don't know why that is so slow (some overhead I haven't optimized). This is related to https://github.com/blaylockbk/Herbie/discussions/40

**Comment by richardgarmong** [comment]
Hey Brian, 
Thanks so much! It actually looks like our server wasn't updated to 0.0.8 which is a part of why I was having problems. It has been updated and your suggestion works perfectly
