### ISSUE TITLE
How to dump GRIB data into a text file.

### ISSUE THREAD

**Issue by CraigglesO** [blaylockbk/Herbie#47]
I am truly aweful at python I can't seem to work with grib outside of python so please don't laugh too hard when you read my code:

```py
from herbie.archive import Herbie
import numpy as np

H = Herbie('2022-01-26', model='ecmwf', product='oper', fxx=12)

ds = H.xarray(':2t:', remove_grib=False)

dsw = H.xarray(':10(u|v):', remove_grib=False)
ds['spd'] = np.sqrt(dsw['u10'] ** 2 + dsw['v10'] ** 2)

dsp = H.xarray(':tp:', remove_grib=False)
ds['tp'] = dsp['tp']

file = open('test.txt', 'a')
for lon in ds['longitude']:
    for lat in ds['latitude']:
        point = ds.sel(longitude=lon, latitude=lat, method='nearest')
        line = str(point['longitude'].values) + ',' + str(point['latitude'].values) + ',' + str(point['t2m'].values) + ',' + str(point['spd'].values) + ',' + str(point['tp'].values) + '\n'
        file.write(line)
file.close()
```

After 5 minutes it was like 5% done. I get why it's bad, but I honestly just don't want to spend a month learning python.

I prefer to just make like a (405900, 5) array and store a raw blob file of float32s like so:

lon1,lat1,t2m1,spd1,tp1,.....,lonN,latN,t2mN,spdN,tpN

Any advice would be amazing.

**Comment by blaylockbk** [comment]
It looks like you are trying to dump data from a GRIB file to a text/csv file. You might consider converting it to a Pandas DataFrame, concatenating the columns, and write the output. Something like this might work. 

```python
from herbie.archive import Herbie
import numpy as np
import pandas as pd

# Get GRIB data as an xarray dataset
H = Herbie('2022-01-26', model='ecmwf', product='oper', fxx=12)
ds1 = H.xarray(':2t:')
ds2 = H.xarray(':10(u|v):')
ds3 = H.xarray(':tp:')

speed = np.sqrt(ds2.u10**2 + ds2.v10**2)

# convert each xarray.Dataset to a Pandas DataFrame
# Then unstack it (convert 2D array to 1D) to a Series.
air_temp = ds1['t2m'].to_pandas().unstack()
spd = speed.to_pandas().unstack()
tp = ds3['unknown'].to_pandas().unstack()

# Build a new DataFrame, (join the data into columns)
new_df = pd.concat(dict(
    air_temperature=air_temp,
    wind_speed=spd,
    total_precipitation=tp
), axis=1)

# Write the DataFrame to a new file
new_df.to_csv('from_grib.csv')
```

You are not the only person who dreads GRIB. The cfgrib python package (what Herbie uses) puts GRIB into an xarray.Dataset, which is really nice to work with. If you haven't spent much time learning xarray, I would recommend learning it. You will find it can do a lot more than you can do with simple csv files.

---
Side note: by not using GRIB, you sacrifice the data compression. Each GRIB field from ECMWF is ~1MB. If you get four variables that is ~5MB of GRIB data. When you turn that into a text file it will be ~28MB. That's not much of a problem if you are looking at a few files, but when you process lots of files, that can grow fast. That is why GRIB is widely used--the data compression is unmatched.

**Comment by CraigglesO** [comment]
Thank you for being so quick with your response! This helped tremendously! It's also insanely fast! I can work on the data now. :)

I originally set `remove_grib=False` because I didn't want to keep pinging the servers while experimenting. But I can do one file at a time and delete the file later.

I honestly wonder though if proto-buffers would have much better compression than GRIB. I think the biggest issue I have with GRIB is the lack of support outside python. Otherwise it's not the worst thing in the world.

I really appreciate your help and I hope this thread helps someone else as well.

If you don't mind me asking before I close this thread, I read a lot of your documentation but it doesn't go into precipitation for GFS. I can't seem to find tutorials online either. It SEEMS like averaging the 1000-500mb range (I don't know what mb is) for CLWMR is the way to do it?

[From this map](https://earth.nullschool.net/#2022/02/19/2100Z/wind/surface/currents/overlay=precip_3hr/orthographic=-76.80,43.03,646) it seems like getting 3-hour precipitation is possible (my goal).

You've already helped me more than enough though, I genuinely appreciate your help thus far.

**Comment by CraigglesO** [comment]
Seems like it's actually just one variable with the newer GFS ":PRATE:surface:". Correct me if I'm wrong though.

**Comment by blaylockbk** [comment]
The PRATE variable is precipitation rate. You might instead want the APCP variable, which is accumulated precipitation. There are usually two fields for APCP, one is accumulated since the last forecast hour, and the other is accumulated since the initialization time.

<html>
<body>


":APCP:surface:0-[1-9]*" | Accumulated precip since initialization time
-- | --
":APCP:surface:[1-9]*-[1-9]*" | Accumulated precip over last hour


</body>
</html>

There is some discussion on the HRRR precipitation variables here: #10

Also, a little more info on the NCEP GRIB table variables you might find useful is here: https://www.nco.ncep.noaa.gov/pmb/docs/on388/table2.html

**Comment by CraigglesO** [comment]
Wow, this (and links) are a great explanation. I appreciate your time and effort immensely!

Will close on this.
