### ISSUE TITLE
Try this: Multithreading for downloading speedup

### ISSUE THREAD

**Issue by blaylockbk** [blaylockbk/Herbie#52]
Would Multithreading help download many files (and many parts of files) quickly? 

This would be a helper tool used in `herbie.tools` (in `bulk_download`) 

Check out this article for some inspiration. 
- https://superfastpython.com/threadpoolexecutor-download-books/
- https://superfastpython.com/threadpoolexecutor-map-vs-submit/

It seems like simply downloading files are parts of files is an IO-bound task that could see some speedup fro multi threading.

Possiblly could see speedup when iterating on downloading chunks of the file.

**Comment by AlexandreBorowczyk** [comment]
Tried it and it works! Here is my code

`        s_t = time.perf_counter()
        datasets = []
        with ThreadPoolExecutor(max_workers=7) as executor:

            futures = [
                executor.submit(Herbie(
                    model_input.date,
                    fxx=fxx,
                    model=cls.model,
                    product=model_input.product,
                    save_dir=model_input.download_dir).xarray,
                                searchString=model_input.search_string,
                                remove_grib=False) for fxx in model_input.fxx
            ]
            datasets = [future.result() for future in as_completed(futures)]

        e_t = time.perf_counter()
        print(f'Download done {e_t-s_t:0.2f} secs')
        c_t = time.perf_counter()
        dataset = xr.concat(datasets, dim="f")
        e_t = time.perf_counter()
        print(f'Concat done {e_t-c_t:0.2f} secs')`

Results for 2 fxx:
MultiThreaded:
`Download done 27.05 secs`
Sequential:
`Download done 44.33 secs`

Search string used:
`"(((U|V)GRD)|(HGT)):(1013\.2|1000|975|950|925|900|875|850|825|800|775|750|725|700|675|650|625|600) mb"`

**Comment by AlexandreBorowczyk** [comment]
Tried using ProcessPoolExecutor vs ThreadPoolExecutor and it's slightly faster

**Comment by blaylockbk** [comment]
Nice! I started playing around with this too. It's fun to learn a new python trick.

My sandbox notebook is [here](https://github.com/blaylockbk/Herbie/blob/blaylockbk/issue52/notebooks/issues/52_multithreading.ipynb)

I found that even creating many Herbie objects can be made much faster with multithreading. Initializing a Herbie object, after all, just tells you where the desired file can be found (which is an I/O-bound task, as is downloading data).

The below gets the F00-F12 forecasts for all hours in a day (288 GRIB2 files)

```python
import pandas as pd

from concurrent.futures import ThreadPoolExecutor
from concurrent.futures import as_completed, wait

# Sequential
DATES = pd.date_range('2021-01-01', periods=24, freq='h')
H = [Herbie(DATE, model='hrrr', product='sfc', fxx=fxx, verbose=False) for DATE in DATES for fxx in range(12)]

# Created 288 Herbie objects in 86 seconds
```

```python
## Use MultThreading to create Herbie objects

with ThreadPoolExecutor(5) as exe:
    futures = [exe.submit(Herbie, DATE, model='hrrr', produce='sfc', fxx=fxx, verbose=False) for DATE in DATES for fxx in range(12)]
    
    # Return list of Herbie objects in order completed
    #data = [future.result() for future in as_completed(futures)]
    
    # Return list of Herbie objects in order submitted
    futures, _ = wait(futures)
    data = [future.result() for future in futures]

# Created 288 Herbie objects in 17 seconds
```

**Comment by blaylockbk** [comment]
didn't mean to close this with that last pull request. But I added some functions that use this. 

I'll add some documentation later.
