### ISSUE TITLE
Interest in Adding Support for NAM Model

### ISSUE THREAD

**Issue by mariandob** [blaylockbk/Herbie#93]
Hi Brian,

I was wondering if there are plans to try and add the North American Mesoscale (NAM) model to the list of models that Herbie works with? I recently found that this data is available through [Amazon Web Services](https://registry.opendata.aws/noaa-nam/) and would think that adding it the list of Herbie compatible models would maybe not be too difficult? I am a relatively novice python programmer, so maybe I am mistaken on this point, but if you are not working on this currently I would be happy to contribute with a small bit guidance on what needs to be done.

Thanks for the excellent documentation on Herbie, and for the package itself. 

Best,

Marian

**Comment by blaylockbk** [comment]
Hi @mariandob 
Thanks for the suggestion. Adding NAM to Herbie was quick. I just added a [template](https://github.com/blaylockbk/Herbie/blob/main/herbie/models/nam.py) file that told Herbie where to look for the data. The default behavior, Herbie will to look for the data at AWS first then Herbie checks NOMADS. The default product is the `conusnest.hiresf`, but it looks like NAM has _lots_ of other product types. 

There is a sample notebook here: https://github.com/blaylockbk/Herbie/blob/main/docs/user_guide/notebooks/data_nam.ipynb

If you need more than this, feel free to make a pull request or comment more here. I can't promise that I'll get around to it as fast as I did this initial addition. When I get around to updating the docs, I'll publish a new release on PyPI.

**Comment by blaylockbk** [comment]
I'll close this for now. But feel free to open again if you need more NAM functionality.
