### ISSUE TITLE
GFS data downloaded with searchString is not complete. Radiation variables are omitted.

### ISSUE THREAD

**Issue by sramirez** [blaylockbk/Herbie#95]
Hi!

I have tried to download some radiation variables from GFS with no success. Some months ago I was able to download this data with the same version (Herbie 0.0.6), however, now it only gives me the following set of allowed variables:

```
array(['PRMSL', 'CLWMR', 'ICMR', 'RWMR', 'SNMR', 'GRLE', 'REFD', 'REFC',
       'VIS', 'UGRD', 'VGRD', 'VRATE', 'GUST', 'HGT', 'TMP', 'RH', 'SPFH',
       'VVEL', 'DZDT', 'ABSV', 'O3MR', 'TCDC', 'HINDEX', 'MSLET', 'PRES',
       'TSOIL', 'SOILW', 'SOILL', 'CNWAT', 'WEASD', 'SNOD', 'ICETK',
       'DPT', 'APTMP', 'ICEG', 'CPOFP', 'PRATE', 'CSNOW', 'CICEP',
       'CFRZR', 'CRAIN', 'SFCR', 'FRICV', 'VEG', 'SOTYP', 'WILT', 'FLDCP',
       'SUNSD', 'LFTX', 'CAPE', 'CIN', 'PWAT', 'CWAT', 'TOZNE', 'LCDC',
       'MCDC', 'HCDC', 'HLCY', 'USTM', 'VSTM', 'ICAHT', 'VWSH', '4LFTX',
       'HPBL', 'POT', 'PLPL', 'LAND', 'ICEC', 'ICETMP'], dtype=object)
```
It is only a small subset of the full set of variables in NOAA GFS. Is not possible to download radiation variables from GFS anymore with Herbie?

**Comment by blaylockbk** [comment]
Can you send me a code snippet of how your are using Herbie? That will help be debug the issue.

**Comment by sramirez** [comment]
Sure. It's pretty simple:

```
>>> herbie = Herbie('2022-08-10', product='pgrb2full.0p50', model='gfs', fxx=0)
✅ Found ┊ model=gfs ┊ product=pgrb2full.0p50 ┊ 2022-Aug-10 00:00 UTC F00 ┊ GRIB2 @ aws ┊ IDX @ aws
>>> herbie.download("DSWRF:surface")
No GRIB messages found. There might be something wrong with searchString='DSWRF:surface'
```

**Comment by sramirez** [comment]
It seems now no forecast is provided for some variables in frequency zero. For instance, for radiation variables.
Some months ago a given frequency X, gives forecast results that spans from X onward (X, X+t), now it is the opposite (X-t, X). So, in Herbie it should be better managed the case for fxx = 0.

**Comment by blaylockbk** [comment]
It looks like the `DSWRF` flux is available in the forecast products, but not the F00 analysis.

See here: https://www.nco.ncep.noaa.gov/pmb/products/gfs/gfs.t00z.pgrb2.0p25.f003.shtml (linked from [here](https://www.nco.ncep.noaa.gov/pmb/products/gfs/))

Thus, 
```python
# DSWRF does *not* exist
H = Herbie('2021-08-10', product="pgrb2.0p25", model='gfs', fxx=0)
```

```python
# DSWRF does exist
H = Herbie('2021-08-10', product="pgrb2.0p25", model='gfs', fxx=1)
```


<img width="803" alt="image" src="https://user-images.githubusercontent.com/6249613/187011119-27fe2743-9149-426e-bdcf-9feb98e8c2af.png">


And I was able to download and plot some data
```python
ds = H.xarray("DSW")
```

<img width="444" alt="image" src="https://user-images.githubusercontent.com/6249613/187011227-f25a9487-4bc7-4774-aac0-d74851bf5210.png">

**Comment by blaylockbk** [comment]
Closing for now, but feel free to reopen if needed.
