### ISSUE TITLE
conda environment.yml install

### ISSUE THREAD

**Issue by jjm0022** [blaylockbk/Herbie#97]
I am trying to install Herbie using the conda `environment.yml` file but conda is finding conflicts that are causing the install to fail:

```
(base) jmiller@ubuntu:~$ conda env create -f environment.yml
Collecting package metadata (repodata.json): done
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:



Package geos conflicts for:
metpy -> cartopy[version='>=0.15.0'] -> shapely[version='>=1.6.4'] -> geos[version='>=3.4']
cartopy[version='>=0.20.3'] -> geos[version='>=3.10.3,<3.10.4.0a0|>=3.11.0,<3.11.1.0a0']
metpy -> cartopy[version='>=0.15.0'] -> geos[version='3.6.2|>=3.10.0,<3.10.1.0a0|>=3.10.1,<3.10.2.0a0|>=3.10.2,<3.10.3.0a0|>=3.10.3,<3.10.4.0a0|>=3.11.0,<3.11.1.0a0|>=3.6.2,<3.6.3.0a0|>=3.7.0,<3.7.1.0a0|>=3.7.1,<3.7.2.0a0|>=3.7.2,<3.7.3.0a0|>=3.8.0,<3.8.1.0a0|>=3.8.1,<3.8.2.0a0|>=3.9.0,<3.9.1.0a0|>=3.9.1,<3.9.2.0a0']
geopandas -> shapely -> geos[version='3.6.2|>=3.10.0,<3.10.1.0a0|>=3.10.1,<3.10.2.0a0|>=3.10.2,<3.10.3.0a0|>=3.10.3,<3.10.4.0a0|>=3.11.0,<3.11.1.0a0|>=3.4|>=3.6.2,<3.6.3.0a0|>=3.7.0,<3.7.1.0a0|>=3.7.1,<3.7.2.0a0|>=3.7.2,<3.7.3.0a0|>=3.8.0,<3.8.1.0a0|>=3.8.1,<3.8.2.0a0|>=3.9.0,<3.9.1.0a0|>=3.9.1,<3.9.2.0a0']
```

I was able to manually create a conda environment and then install using `pip`

UPDATE:
Turns out the conda environment I set up using `pip` actually doesn't want to work either. I'll keep trying and see if I can get it working.

**Comment by blaylockbk** [comment]
Thanks for reporting this. Sounds like there are some install issues that I haven't properly tested for. Seems like there is an issue with the dependencies between the required packages.

What platform are you trying to install on?

**Comment by jjm0022** [comment]
Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-189-generic x86_64)

**Comment by blaylockbk** [comment]
Hi @jjm0022 

I tweeked the environment file so that it only includes the minimum dependencies. This might help your case.

I haven't had a chance to test it on Linux yet, but the [updated installation instructions](https://github.com/blaylockbk/Herbie#installation) worked on my Windows PC.

(Doing some CI and making a conda-forge recipe for Herbie has been on my to-do list for at least a year, haha)

**Comment by blaylockbk** [comment]
Closing this for now, but please reopen if you still have troubles installing Herbie.

Note: Herbie can now be installed with conda
```
conda install -c conda-forge herbie-data
```
